import { Header } from '@/components/layout/header';
import { ThemeProvider } from '@/components/theme/theme-provider';
import { BackgroundCursor } from '@/components/ui/background-cursor';
import { fontInter } from '@/config/font';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={cn(fontInter.variable, 'h-full font-family-sans')}
            suppressHydrationWarning
        >
            <body className='antialiased h-full flex flex-col gap-6'>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <BackgroundCursor>
                        <div className='w-full h-full flex flex-col'>
                            <Header />
                            {children}
                        </div>
                    </BackgroundCursor>
                </ThemeProvider>
            </body>
        </html>
    );
}
